# -*- mode: ruby -*-
# vi: set ft=ruby :

###################################
Vagrant.configure("2") do |config|
    # config server
    config.vm.define "ansible-python-node" do |config|
      config.vm.box = "ubuntu/trusty64"
      config.ssh.insert_key = false
      config.vm.network "private_network", ip: "192.168.10.111",
        auto_config: true
      config.vm.network "forwarded_port", guest: 80 , host: 4000, host_ip: "127.0.0.1"
      config.vm.hostname = "ansible-python-node"
      config.vm.provider "virtualbox" do |vb|
        # Customize VM
        vb.name = "python-box"
        vb.memory = "1024"
        vb.cpus = "1"
      end

      # Provision with Ansible
      config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "playbooks/main.yml"
      end

    end
end
